[project]
name = "traceai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shreyas19205", email = "shreyas0962@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
traceai = "traceai:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
